# Generated by Django 5.0.6 on 2025-03-07 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('merchant', 'merchant'), ('service_provider', 'service_provider')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('home_cleaning', 'Home Cleaning'), ('office_cleaning', 'Office Cleaning'), ('carpet_cleaning', 'Carpet Cleaning'), ('window_cleaning', 'Window Cleaning'), ('deep_cleaning', 'Deep Cleaning')], max_length=255)),
                ('rate_per_hour', models.FloatField()),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField(auto_now_add=True)),
                ('booked_date', models.DateField()),
                ('approve', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_book', to='home.service')),
            ],
        ),
    ]
