# Generated by Django 5.0.6 on 2025-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_role_service_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
